"""Initial tables

Revision ID: ccf96071c656
Revises: 
Create Date: 2023-09-22 12:26:14.395678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ccf96071c656'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processing_request',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('creation_time', sa.DateTime(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('input_assets_ids', postgresql.ARRAY(sa.Uuid()), nullable=False),
    sa.Column('output_assets_ids', postgresql.ARRAY(sa.Uuid()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processing_request_creation_time'), 'processing_request', ['creation_time'], unique=False)
    op.create_index(op.f('ix_processing_request_end_time'), 'processing_request', ['end_time'], unique=False)
    op.create_index(op.f('ix_processing_request_input_assets_ids'), 'processing_request', ['input_assets_ids'], unique=False)
    op.create_index(op.f('ix_processing_request_output_assets_ids'), 'processing_request', ['output_assets_ids'], unique=False)
    op.create_index(op.f('ix_processing_request_project_id'), 'processing_request', ['project_id'], unique=False)
    op.create_index(op.f('ix_processing_request_start_time'), 'processing_request', ['start_time'], unique=False)
    op.create_index(op.f('ix_processing_request_status'), 'processing_request', ['status'], unique=False)
    op.create_index(op.f('ix_processing_request_type'), 'processing_request', ['type'], unique=False)
    op.create_index(op.f('ix_processing_request_user_id'), 'processing_request', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_processing_request_user_id'), table_name='processing_request')
    op.drop_index(op.f('ix_processing_request_type'), table_name='processing_request')
    op.drop_index(op.f('ix_processing_request_status'), table_name='processing_request')
    op.drop_index(op.f('ix_processing_request_start_time'), table_name='processing_request')
    op.drop_index(op.f('ix_processing_request_project_id'), table_name='processing_request')
    op.drop_index(op.f('ix_processing_request_output_assets_ids'), table_name='processing_request')
    op.drop_index(op.f('ix_processing_request_input_assets_ids'), table_name='processing_request')
    op.drop_index(op.f('ix_processing_request_end_time'), table_name='processing_request')
    op.drop_index(op.f('ix_processing_request_creation_time'), table_name='processing_request')
    op.drop_table('processing_request')
    # ### end Alembic commands ###
