{
 "title": "Default",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Users Registered",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "new_users_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "User Logins",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(user_logins_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "User Verifications",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "user_verifications_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "API Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by() (requests_total{exported_job=\"api_server\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Server Logs [ERROR]",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{service_name=\"api_server\", level=\"ERROR\"} |= ``"
    }
   ]
  },
  {
   "title": "Simod Worker Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "{service_name=\"bps-discovery-simod\"} |= ``"
    }
   ]
  },
  {
   "title": "Kronos Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{service_name=\"waiting_time_analysis_kronos\"} |= ``"
    }
   ]
  },
  {
   "title": "Prosimos Worker Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "{service_name=\"simulation-prosimos\"} |= ``"
    }
   ]
  }
 ]
}