### Get a JWT

POST http://localhost:8000/auth/jwt/login
Content-Type: application/x-www-form-urlencoded

username = {{user_name}} &
password = {{user_password}}

### User profile

GET http://localhost:8000/users/me
Authorization: Bearer {{token}}

### Create a user

POST http://localhost:8000/auth/register
Content-Type: application/json

{
  "email": "ihar.suvorau@gmail.com",
  "password": "123",
  "first_name": "Ihar",
  "last_name": "Suvorau"
}

### List projects

GET http://localhost:8000/projects/
Authorization: Bearer {{token}}

### Add a project

POST http://localhost:8000/projects/
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "project one"
}
