@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0OGRkNTdjNi05ZDdkLTQ1ZmYtOWJlMC0yMTQyNmViMGIzMmUiLCJhdWQiOlsiZmFzdGFwaS11c2VyczphdXRoIl0sImV4cCI6MTY5NTMwNDk0M30.E7qH7MkUuxXOHvT3aALIOyPuT01WxJFlB2zwtiaH9MI

###

GET http://localhost:8010/files/
Authorization: Bearer foo

###

POST http://localhost:8010/files/
Authorization: Bearer {{token}}
Content-Type: application/octet-stream

< ./requirements.txt

###

POST http://localhost:8000/auth/jwt/login
Content-Type: application/x-www-form-urlencoded

username=foo@bar.com&password=1234