"""Initial tables

Revision ID: 34ddacd8328c
Revises: 
Create Date: 2023-09-21 14:26:45.465118

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "34ddacd8328c"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("creation_time", sa.DateTime(), nullable=False),
        sa.Column("modification_time", sa.DateTime(), nullable=True),
        sa.Column("deletion_time", sa.DateTime(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("users_ids", postgresql.ARRAY(sa.Uuid()), nullable=False),
        sa.Column("assets_ids", postgresql.ARRAY(sa.Uuid()), nullable=False),
        sa.Column(
            "processing_requests_ids", postgresql.ARRAY(sa.Uuid()), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_project_assets_ids"), "project", ["assets_ids"], unique=False
    )
    op.create_index(
        op.f("ix_project_creation_time"), "project", ["creation_time"], unique=False
    )
    op.create_index(
        op.f("ix_project_deletion_time"), "project", ["deletion_time"], unique=False
    )
    op.create_index(
        op.f("ix_project_modification_time"),
        "project",
        ["modification_time"],
        unique=False,
    )
    op.create_index(op.f("ix_project_name"), "project", ["name"], unique=False)
    op.create_index(
        op.f("ix_project_processing_requests_ids"),
        "project",
        ["processing_requests_ids"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_users_ids"), "project", ["users_ids"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_project_users_ids"), table_name="project")
    op.drop_index(op.f("ix_project_processing_requests_ids"), table_name="project")
    op.drop_index(op.f("ix_project_name"), table_name="project")
    op.drop_index(op.f("ix_project_modification_time"), table_name="project")
    op.drop_index(op.f("ix_project_deletion_time"), table_name="project")
    op.drop_index(op.f("ix_project_creation_time"), table_name="project")
    op.drop_index(op.f("ix_project_assets_ids"), table_name="project")
    op.drop_table("project")
    # ### end Alembic commands ###
