"""Add many-to-many files relationship, and name column

Revision ID: 1ec8f6045673
Revises: 3afd6413720c
Create Date: 2023-11-06 13:37:59.504177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ec8f6045673'
down_revision: Union[str, None] = '3afd6413720c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('creation_time', sa.DateTime(), nullable=False),
    sa.Column('deletion_time', sa.DateTime(), nullable=True),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assets_files',
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('file_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['file_id'], ['file.id'], ),
    sa.PrimaryKeyConstraint('asset_id', 'file_id')
    )
    op.drop_column('asset', 'file_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset', sa.Column('file_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_table('assets_files')
    op.drop_table('file')
    # ### end Alembic commands ###
