"""Change many-to-many files relationship to implicit one

Revision ID: 97e8e23beefd
Revises: 1ec8f6045673
Create Date: 2023-11-06 15:00:35.838046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '97e8e23beefd'
down_revision: Union[str, None] = '1ec8f6045673'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assets_files')
    op.drop_table('file')
    op.add_column('asset', sa.Column('users_ids', postgresql.ARRAY(sa.Uuid()), nullable=False))
    op.add_column('asset', sa.Column('files_ids', postgresql.ARRAY(sa.Uuid()), nullable=False))
    op.create_index(op.f('ix_asset_processing_requests_ids'), 'asset', ['processing_requests_ids'], unique=False)
    op.create_index(op.f('ix_asset_users_ids'), 'asset', ['users_ids'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_asset_users_ids'), table_name='asset')
    op.drop_index(op.f('ix_asset_processing_requests_ids'), table_name='asset')
    op.drop_column('asset', 'files_ids')
    op.drop_column('asset', 'users_ids')
    op.create_table('file',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('creation_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('deletion_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('content_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='file_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('assets_files',
    sa.Column('asset_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('file_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], name='assets_files_asset_id_fkey'),
    sa.ForeignKeyConstraint(['file_id'], ['file.id'], name='assets_files_file_id_fkey'),
    sa.PrimaryKeyConstraint('asset_id', 'file_id', name='assets_files_pkey')
    )
    # ### end Alembic commands ###
