### Get a JWT

POST http://localhost:9999/api/v1/auth/jwt/login
Content-Type: application/x-www-form-urlencoded

username = ihar.suvorau@gmail.com &
password = 123

### List files

GET http://localhost:9999/api/v1/files/
Authorization: Bearer {{token}}

### Add a file

POST http://localhost:9999/api/v1/files/
Authorization: Bearer {{token}}
Content-Type: application/octet-stream

< ./compose.yaml

### Get a file

GET http://localhost:9999/api/v1/files/716d979b-d7ac-4cd9-99da-8566f70576f1/location
Authorization: Bearer {{token}}