### List projects

GET http://localhost:9999/api/v1/projects/
Authorization: Bearer {{token}}

### List projects for a user

GET http://localhost:9999/api/v1/projects/?user_id=56c7e847-4108-4949-af14-34a513dd1a75
Authorization: Bearer {{token}}

### Add a project

POST http://localhost:9999/api/v1/projects/
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "project one"
}

### Get a project

GET http://localhost:9999/api/v1/projects/c012fd4b-8cf1-4335-ae76-cac069e4a9ef
Authorization: Bearer {{token}}

### Get project assets

GET http://localhost:9999/api/v1/projects/c012fd4b-8cf1-4335-ae76-cac069e4a9ef/assets
Authorization: Bearer {{token}}

### Update a project

PATCH http://localhost:8030/projects/725c14d3-df43-4666-9c8d-f316546471d2
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "foo"
}

### Add an asset to a project

POST http://localhost:8030/projects/6eb59a7b-a476-4a4b-a9a8-46963693c5e5/assets
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "asset_id": "fb97326a-b762-4e5a-932d-bdd4cca3db96"
}

### Remove an asset from a project

DELETE http://localhost:8030/projects/6eb59a7b-a476-4a4b-a9a8-46963693c5e5/assets/fb97326a-b762-4e5a-932d-bdd4cca3db96
Content-Type: application/json
Authorization: Bearer {{token}}