### Get a JWT

POST http://localhost:9999/api/v1/auth/jwt/login
Content-Type: application/x-www-form-urlencoded

username = ihar.suvorau@gmail.com &
password = 123

### Get a JWT

POST http://localhost:9999/api/v1/auth/jwt/login
Content-Type: application/x-www-form-urlencoded

username = system@pix.cloud.ut.ee &
password = system

### List projects

GET http://localhost:9999/api/v1/projects/?user_id=e431ca4d-4df3-42f4-b011-27d40ffa40ff
Content-Type: application/json
Authorization: Bearer {{token}}

### Get a project

GET http://localhost:9999/api/v1/projects/536b9d58-83b9-4251-ba87-5432ec9f0a8b
Content-Type: application/json
Authorization: Bearer {{token}}

### Create a project

POST http://localhost:9999/api/v1/projects/
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Simod Run"
}

### Upload an event log

POST http://localhost:9999/api/v1/files/?name=PurchasingExample.csv.gz&type=event_log_csv_gz
Authorization: Bearer {{token}}
Content-Type: application/octet-stream

< ./PurchasingExample.csv.gz

### Upload a column mapping

POST http://localhost:9999/api/v1/files/?name=column_mapping.json&type=event_log_column_mapping_json
Authorization: Bearer {{token}}
Content-Type: application/octet-stream

< ./column_mapping.json

### Upload the configuration

POST http://localhost:9999/api/v1/files/?name=configuration_one_shot.yml&type=configuration_simod_yaml
Authorization: Bearer {{token}}
Content-Type: application/octet-stream

< ./configuration_one_shot.yml

### Create the event log asset

POST http://localhost:9999/api/v1/assets/
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "PurchasingExample.csv.gz",
  "type": "event_log",
  "files_ids": [
    "cca1c04f-1943-4e67-b6fb-9526e86ecb0c",
    "b189919e-67fc-4764-9002-689fcc65f02d"
  ],
  "project_id": "9da8ed0b-1f3b-44b0-ab6e-f9319ef45e75"
}

### Create the configuration asset

POST http://localhost:9999/api/v1/assets/
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "configuration_one_shot.yml",
  "type": "simod_configuration",
  "files_ids": [
    "ecce6a24-8e49-4c8c-a48a-a11a8f502ed4"
  ],
  "project_id": "9da8ed0b-1f3b-44b0-ab6e-f9319ef45e75"
}

### List assets

GET http://localhost:9999/api/v1/assets/?project_id=536b9d58-83b9-4251-ba87-5432ec9f0a8b
Authorization: Bearer {{token}}

### Create a new processing request

POST http://localhost:9999/api/v1/processing-requests/
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "type": "process_model_optimization_simod",
  "project_id": "9da8ed0b-1f3b-44b0-ab6e-f9319ef45e75",
  "input_assets_ids": [
    "19045307-f284-4003-a5f6-da0e9094c94c",
    "50277fe2-fe19-445c-8254-53daae5eca83"
  ],
  "should_notify": true
}

### Get a processing request

GET http://localhost:9999/api/v1/processing-requests/d0846ce5-c022-496c-9bc2-c25cec4de74b
Authorization: Bearer {{token}}

### Get a file

GET http://localhost:9999/api/v1/files/cca1c04f-1943-4e67-b6fb-9526e86ecb0c
Authorization: Bearer {{token}}
