### Get a JWT

POST http://localhost:9999/api/v1/auth/jwt/login
Content-Type: application/x-www-form-urlencoded

username = ihar.suvorau@gmail.com &
password = 123

### Get a JWT

POST http://localhost:9999/api/v1/auth/jwt/login
Content-Type: application/x-www-form-urlencoded

username = system@pix.cloud.ut.ee &
password = system

### List projects

GET http://localhost:9999/api/v1/projects/?user_id=e431ca4d-4df3-42f4-b011-27d40ffa40ff
Content-Type: application/json
Authorization: Bearer {{token}}

### Create a project

POST http://localhost:9999/api/v1/projects/
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Prosimos Run"
}

### Upload a file

POST http://localhost:9999/api/v1/files/
Authorization: Bearer {{token}}
Content-Type: application/octet-stream

< ./configuration_prosimos.yml

### List files

GET http://localhost:9999/api/v1/files/
Authorization: Bearer {{token}}

### Upload the simulation model

POST http://localhost:9999/api/v1/files/
Authorization: Bearer {{token}}
Content-Type: application/octet-stream

< ./PurchasingExampleSimulationModel.json

### Create the process model asset

POST http://localhost:9999/api/v1/assets/
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "PurchasingExample.bpmn",
  "type": "process_model_bpmn",
  "file_id": "9df58316-cfcb-4f06-8c47-f2102648a4db",
  "project_id": "9da8ed0b-1f3b-44b0-ab6e-f9319ef45e75"
}

### Create the simulation model asset

POST http://localhost:9999/api/v1/assets/
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "PurchasingExampleSimulationModel.json",
  "type": "simulation_model_prosimos_json",
  "file_id": "1aa19b4a-a65f-4aa4-ac5f-d76ccd10dfdc",
  "project_id": "9da8ed0b-1f3b-44b0-ab6e-f9319ef45e75"
}

### Create the prosimos configuration asset

POST http://localhost:9999/api/v1/assets/
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "configuration_prosimos.yml",
  "type": "configuration_prosimos_yaml",
  "file_id": "32642de3-33d7-415a-9693-42a3e245e6bf",
  "project_id": "9da8ed0b-1f3b-44b0-ab6e-f9319ef45e75"
}

### Get an asset

GET http://localhost:9999/api/v1/assets/9777218c-99c5-4704-aa12-b5e4ad5ac0be
Authorization: Bearer {{token}}

### List assets

GET http://localhost:9999/api/v1/assets/?project_id=536b9d58-83b9-4251-ba87-5432ec9f0a8b
Authorization: Bearer {{token}}

### Create a new processing request

POST http://localhost:9999/api/v1/processing-requests/
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "type": "simulation_prosimos",
  "project_id": "9da8ed0b-1f3b-44b0-ab6e-f9319ef45e75",
  "input_assets_ids": [
    "9777218c-99c5-4704-aa12-b5e4ad5ac0be"
  ],
  "should_notify": true
}

### Get a processing request

GET http://localhost:9999/api/v1/processing-requests/c4b1355d-8551-4a7a-9f37-06e11daa4f38
Authorization: Bearer {{token}}

### Get resulting asset

GET http://localhost:9999/api/v1/assets/9f0a9d24-9fec-4824-850c-f8555cb7d79e/location?is_internal=false
Authorization: Bearer {{token}}

### Get the blob

GET http://localhost:9999/api/v1/blobs/c5134a3dd63bb722dbe6741509a559aedbf6a965fb2bf102df3d982072a6d742
Authorization: Bearer {{token}}