### Get a JWT

POST http://localhost:9999/api/v1/auth/jwt/login
Content-Type: application/x-www-form-urlencoded

username = baz@bar.com &
password = 123

### Get a JWT

POST http://localhost:9999/api/v1/auth/jwt/login
Content-Type: application/x-www-form-urlencoded

username = system@pix.cloud.ut.ee &
password = system

### List projects

GET http://localhost:9999/api/v1/projects/
Content-Type: application/json
Authorization: Bearer {{token}}

### Create a project

POST http://localhost:9999/api/v1/projects/
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "project one"
}

### Upload a file

POST http://localhost:9999/api/v1/files/
Authorization: Bearer {{token}}
Content-Type: application/octet-stream

< ./configuration_prosimos.yml

### List files

GET http://localhost:9999/api/v1/files/
Authorization: Bearer {{token}}

### Upload the simulation model

POST http://localhost:9999/api/v1/files/
Authorization: Bearer {{token}}
Content-Type: application/octet-stream

< ./PurchasingExampleSimulationModel.json

### Create an asset

POST http://localhost:9999/api/v1/assets/
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "configuration_prosimos.yml",
  "type": "configuration_prosimos_yaml",
  "file_id": "32642de3-33d7-415a-9693-42a3e245e6bf",
  "project_id": "775eb3ef-350b-4445-9229-3ea57d9d09c6"
}

### Create the configuration asset

POST http://localhost:9999/api/v1/assets/
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "configuration_one_shot.yml",
  "type": "configuration_simod_yaml",
  "file_id": "f680742c-8409-4972-8bc8-c5069f0e28be",
  "project_id": "775eb3ef-350b-4445-9229-3ea57d9d09c6"
}

### Get an asset

GET http://localhost:9999/api/v1/assets/b6428878-3129-431f-ab58-c3a4f5ab9bf1/location?is_internal=true
Authorization: Bearer {{token}}

### List assets

GET http://localhost:9999/api/v1/assets/
Authorization: Bearer {{token}}

### Create a new processing request

POST http://localhost:9999/api/v1/processing-requests/
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "type": "simulation_prosimos",
  "project_id": "775eb3ef-350b-4445-9229-3ea57d9d09c6",
  "input_assets_ids": [
    "f2f99fc7-e642-4950-a66c-91af4c2c94d5",
    "b6428878-3129-431f-ab58-c3a4f5ab9bf1",
    "e74364c0-546b-4172-b6a1-4f17c3588bc2"
  ]
}

### Get a processing request

GET http://localhost:9999/api/v1/processing-requests/c4b1355d-8551-4a7a-9f37-06e11daa4f38
Authorization: Bearer {{token}}

### Get resulting asset

GET http://localhost:9999/api/v1/assets/9f0a9d24-9fec-4824-850c-f8555cb7d79e/location?is_internal=false
Authorization: Bearer {{token}}

### Get the blob

GET http://localhost:9999/api/v1/blobs/c5134a3dd63bb722dbe6741509a559aedbf6a965fb2bf102df3d982072a6d742
Authorization: Bearer {{token}}