"""Add users IDs column

Revision ID: c20931a9e65b
Revises: 1691d64383ae
Create Date: 2023-11-06 17:09:29.973462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c20931a9e65b'
down_revision: Union[str, None] = '1691d64383ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('users_ids', postgresql.ARRAY(sa.Uuid()), nullable=False))
    op.create_index(op.f('ix_file_users_ids'), 'file', ['users_ids'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_users_ids'), table_name='file')
    op.drop_column('file', 'users_ids')
    # ### end Alembic commands ###
