"""Initial revision

Revision ID: 1d986418089e
Revises: 
Create Date: 2023-12-28 12:15:10.601165

"""
from typing import Sequence, Union

import fastapi_users_db_sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1d986418089e"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "asset",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("creation_time", sa.DateTime(), nullable=False),
        sa.Column("modification_time", sa.DateTime(), nullable=True),
        sa.Column("deletion_time", sa.DateTime(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("users_ids", postgresql.ARRAY(sa.Uuid()), nullable=False),
        sa.Column("files_ids", postgresql.ARRAY(sa.Uuid()), nullable=False),
        sa.Column("processing_requests_ids", postgresql.ARRAY(sa.Uuid()), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_asset_processing_requests_ids"), "asset", ["processing_requests_ids"], unique=False)
    op.create_index(op.f("ix_asset_users_ids"), "asset", ["users_ids"], unique=False)
    op.create_table(
        "file",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("creation_time", sa.DateTime(), nullable=False),
        sa.Column("deletion_time", sa.DateTime(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("content_hash", sa.String(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("users_ids", postgresql.ARRAY(sa.Uuid()), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_file_users_ids"), "file", ["users_ids"], unique=False)
    op.create_table(
        "project",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("creation_time", sa.DateTime(), nullable=False),
        sa.Column("modification_time", sa.DateTime(), nullable=True),
        sa.Column("deletion_time", sa.DateTime(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("users_ids", postgresql.ARRAY(sa.Uuid()), nullable=False),
        sa.Column("assets_ids", postgresql.ARRAY(sa.Uuid()), nullable=False),
        sa.Column("processing_requests_ids", postgresql.ARRAY(sa.Uuid()), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_project_assets_ids"), "project", ["assets_ids"], unique=False)
    op.create_index(op.f("ix_project_creation_time"), "project", ["creation_time"], unique=False)
    op.create_index(op.f("ix_project_deletion_time"), "project", ["deletion_time"], unique=False)
    op.create_index(op.f("ix_project_modification_time"), "project", ["modification_time"], unique=False)
    op.create_index(op.f("ix_project_name"), "project", ["name"], unique=False)
    op.create_index(op.f("ix_project_processing_requests_ids"), "project", ["processing_requests_ids"], unique=False)
    op.create_index(op.f("ix_project_users_ids"), "project", ["users_ids"], unique=False)
    op.create_table(
        "user",
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("last_name", sa.String(), nullable=False),
        sa.Column("creation_time", sa.DateTime(), nullable=False),
        sa.Column("modification_time", sa.DateTime(), nullable=True),
        sa.Column("deletion_time", sa.DateTime(), nullable=True),
        sa.Column("last_login_time", sa.DateTime(), nullable=True),
        sa.Column("id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("hashed_password", sa.String(length=1024), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_table(
        "processing_request",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("creation_time", sa.DateTime(), nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=True),
        sa.Column("end_time", sa.DateTime(), nullable=True),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("message", sa.String(), nullable=True),
        sa.Column("should_notify", sa.Boolean(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("input_assets_ids", postgresql.ARRAY(sa.Uuid()), nullable=False),
        sa.Column("output_assets_ids", postgresql.ARRAY(sa.Uuid()), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_processing_request_creation_time"), "processing_request", ["creation_time"], unique=False)
    op.create_index(op.f("ix_processing_request_end_time"), "processing_request", ["end_time"], unique=False)
    op.create_index(
        op.f("ix_processing_request_input_assets_ids"), "processing_request", ["input_assets_ids"], unique=False
    )
    op.create_index(
        op.f("ix_processing_request_output_assets_ids"), "processing_request", ["output_assets_ids"], unique=False
    )
    op.create_index(op.f("ix_processing_request_project_id"), "processing_request", ["project_id"], unique=False)
    op.create_index(op.f("ix_processing_request_start_time"), "processing_request", ["start_time"], unique=False)
    op.create_index(op.f("ix_processing_request_status"), "processing_request", ["status"], unique=False)
    op.create_index(op.f("ix_processing_request_type"), "processing_request", ["type"], unique=False)
    op.create_index(op.f("ix_processing_request_user_id"), "processing_request", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_processing_request_user_id"), table_name="processing_request")
    op.drop_index(op.f("ix_processing_request_type"), table_name="processing_request")
    op.drop_index(op.f("ix_processing_request_status"), table_name="processing_request")
    op.drop_index(op.f("ix_processing_request_start_time"), table_name="processing_request")
    op.drop_index(op.f("ix_processing_request_project_id"), table_name="processing_request")
    op.drop_index(op.f("ix_processing_request_output_assets_ids"), table_name="processing_request")
    op.drop_index(op.f("ix_processing_request_input_assets_ids"), table_name="processing_request")
    op.drop_index(op.f("ix_processing_request_end_time"), table_name="processing_request")
    op.drop_index(op.f("ix_processing_request_creation_time"), table_name="processing_request")
    op.drop_table("processing_request")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    op.drop_index(op.f("ix_project_users_ids"), table_name="project")
    op.drop_index(op.f("ix_project_processing_requests_ids"), table_name="project")
    op.drop_index(op.f("ix_project_name"), table_name="project")
    op.drop_index(op.f("ix_project_modification_time"), table_name="project")
    op.drop_index(op.f("ix_project_deletion_time"), table_name="project")
    op.drop_index(op.f("ix_project_creation_time"), table_name="project")
    op.drop_index(op.f("ix_project_assets_ids"), table_name="project")
    op.drop_table("project")
    op.drop_index(op.f("ix_file_users_ids"), table_name="file")
    op.drop_table("file")
    op.drop_index(op.f("ix_asset_users_ids"), table_name="asset")
    op.drop_index(op.f("ix_asset_processing_requests_ids"), table_name="asset")
    op.drop_table("asset")
    # ### end Alembic commands ###
