"""Drop _ids indices

Revision ID: 27cfc76f5551
Revises: 1d986418089e
Create Date: 2024-01-23 13:49:42.810177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27cfc76f5551'
down_revision: Union[str, None] = '1d986418089e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_asset_processing_requests_ids', table_name='asset')
    op.drop_index('ix_asset_users_ids', table_name='asset')
    op.drop_index('ix_file_users_ids', table_name='file')
    op.drop_index('ix_processing_request_input_assets_ids', table_name='processing_request')
    op.drop_index('ix_processing_request_output_assets_ids', table_name='processing_request')
    op.drop_index('ix_project_assets_ids', table_name='project')
    op.drop_index('ix_project_processing_requests_ids', table_name='project')
    op.drop_index('ix_project_users_ids', table_name='project')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_project_users_ids', 'project', ['users_ids'], unique=False)
    op.create_index('ix_project_processing_requests_ids', 'project', ['processing_requests_ids'], unique=False)
    op.create_index('ix_project_assets_ids', 'project', ['assets_ids'], unique=False)
    op.create_index('ix_processing_request_output_assets_ids', 'processing_request', ['output_assets_ids'], unique=False)
    op.create_index('ix_processing_request_input_assets_ids', 'processing_request', ['input_assets_ids'], unique=False)
    op.create_index('ix_file_users_ids', 'file', ['users_ids'], unique=False)
    op.create_index('ix_asset_users_ids', 'asset', ['users_ids'], unique=False)
    op.create_index('ix_asset_processing_requests_ids', 'asset', ['processing_requests_ids'], unique=False)
    # ### end Alembic commands ###
