### Get a JWT

POST http://localhost:8000/auth/jwt/login
Content-Type: application/x-www-form-urlencoded

username={{user_name}}&password={{user_password}}

### User profile

GET http://localhost:8000/users/me
Authorization: Bearer {{token}}

### Create a user

POST http://localhost:8000/auth/register
Content-Type: application/json

{
  "email": "ihar.suvorau@gmail.com",
  "password": "123",
  "first_name": "Ihar",
  "last_name": "Suvorau"
}

### Verify email

POST http://localhost:8000/auth/request-verify-token
Content-Type: application/json

{
  "email": "foo@example.com"
}

### Delete user

DELETE http://localhost:8000/users/
Authorization: Bearer {{token}}

### List projects

GET http://localhost:8000/projects/
Authorization: Bearer {{token}}

### Add a project

POST http://localhost:8000/projects/
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "project one"
}

### Get user's projects

GET http://localhost:8000/projects/?user_id=85f310ce-7404-4e36-93a7-52f87b99b96e
Authorization: Bearer {{token}}


### Get assets

GET http://localhost:8000/assets/cba8a5e0-baa1-40b0-a946-6cf534a97762?lazy=false
Authorization: Bearer {{token}}

### Get processing request

GET http://localhost:8000/processing-requests/abe4e895-3a8c-4117-91d9-cda3b210c174/output-assets
Authorization: Bearer {{token}}