@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0OGRkNTdjNi05ZDdkLTQ1ZmYtOWJlMC0yMTQyNmViMGIzMmUiLCJhdWQiOlsiZmFzdGFwaS11c2VyczphdXRoIl0sImV4cCI6MTY5NTMwNTAxMX0.8A6Wtuf1HRt6rj9QWbUKRBX2u3IpefwNx-UHTtsZz9o

###

GET http://localhost:8020/assets/
Authorization: Bearer {{token}}

###

POST http://localhost:8020/assets/
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "requirements.txt",
    "type": "event_log_csv",
    "file_id": "411aac8c-a236-4248-b3f6-d80e6ee4c536",
    "project_id": "6eb59a7b-a476-4a4b-a9a8-46963693c5e5"
}

###

PATCH http://localhost:8020/assets/f00666bf-06c4-4ae5-98aa-6f4ad7bb40cf
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "foo"
}

###

GET http://localhost:8020/assets/d44ab3ed-0516-4c86-9f9a-110542c96fb0/location
Content-Type: application/json
Authorization: Bearer {{token}}

###

POST http://localhost:8000/auth/jwt/login
Content-Type: application/x-www-form-urlencoded

username=foo@bar.com&password=1234